spring:
  application:
    name: airline-reservation

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:h2:file:./db/airline;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: never

  freemarker:
    expose-session-attributes: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    kg.attractor: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8080